 name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Animated Website Deploying to surge
    steps:
    - uses: actions/checkout@v2
      
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  
    - name: Install surge
      run: npm install --global surge 
     
    - name: Deploy to surge
      run: surge ./ animationbymuhibullahkamali.surge.sh --token ${{secrets.SURGE_SECRET}}
